version: "2.3"
services:
  jupyter:
    image: sammrai/jupyter:latest
    container_name: jupyter
    working_dir: /home/jovyan/work
    volumes:
      - ./data:/home/jovyan/work
      - ./dataset:/dataset
      - /etc/localtime:/etc/localtime:ro
      - /data:/data
    ports:
      - 8887:8888
      - 6006:6006
    user: 1000:1000
    restart: unless-stopped
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - PYTHONPATH=/home/jovyan/work/mltlib
      - WORKDIR=/home/jovyan/work
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - TZ=Asia/Tokyo
    runtime: nvidia
    command: jupyter-lab --no-browser --ip 0.0.0.0 --allow-root --no-browser --NotebookApp.disable_check_xsrf=True  --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.terminado_settings='{"shell_command":["/bin/bash"]}' /home/jovyan/work
    mem_limit: 13g
